config/routes.rb
Rails.application.routes.draw do
  root "staticpages#top"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: %i[new create]
  # resources :boards, only: %i[index new create destroy]
  get 'login', to: 'user_session#new'
  post 'login', to: 'user_session#create'
  delete 'logout', to: 'user_session#destroy'
  get "up" => "rails/health#show", as: :rails_health_check
  # 追加 新しいguest_majorレコードを作成する
  resources :guest_majors, only: [:create]
  # 追加 ランダムにboardを2つ選び、それらをJSON形式で返す
  get 'boards/random', to: 'boards#random_boards'
  get 'boards/which_major', to: 'boards#which_major'
  resources :boards do
    resource :majors, only: [:create, :destroy]
    resource :minors, only: [:create, :destroy]
  end
  
end

app/controllers/user_session_controller.rb
class UserSessionController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def create
    @user = login(params[:email], params[:password])
    
    if @user
      flash[:success] = t('user_session.login_success')
      redirect_to boards_path
    else
      flash.now[:danger] = I18n.t('user_session.login_failure')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    flash[:success] = I18n.t('user_session.logout_success')
    redirect_to root_path, status: :see_other
  end
end

app/views/user_session/new.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2 mt-5">
      <h1>ログイン</h1>
      <%= form_with url: login_path, local: true do |f| %>
        <div class="form-group mt-3">
          <%= f.label :email, t('activerecord.attributes.user.email') %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group mt-3">
          <%= f.label :password, t('activerecord.attributes.user.password') %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit 'ログイン', class: 'btn btn-primary btn-lg mt-5' %>
        </div>
      <% end %>
      <div class='text-center mt-3'>
        <%= link_to 'RR 新規ユーザー登録', new_user_path, class:"btn btn-outline-primary" %>
        <%= link_to 'パスワードの再発行', '#', class:"btn btn-outline-primary" %>
      </div>
    </div>
  </div>
</div>