config/routes.rb
Rails.application.routes.draw do
  root "staticpages#top"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: %i[new create]
  # resources :boards, only: %i[index new create destroy]
  get 'login', to: 'user_session#new'
  post 'login', to: 'user_session#create'
  delete 'logout', to: 'user_session#destroy'
  get "up" => "rails/health#show", as: :rails_health_check
  # 追加 新しいguest_majorレコードを作成する
  resources :guest_majors, only: [:create]
  # 追加 ランダムにboardを2つ選び、それらをJSON形式で返す
  get 'boards/random', to: 'boards#random_boards'
  get 'boards/which_major', to: 'boards#which_major'
  resources :boards do
    resource :majors, only: [:create, :destroy]
    resource :minors, only: [:create, :destroy]
  end
  
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation bg-dark" data-bs-theme="dark">
    <%= link_to root_path, class: 'navbar-brand' do %>
    <%= image_tag 'logo.png', width:50%>
    <% end %>
    <div class = "navbar-text">Reality Reflections ~あるあるを寄せ合うSNS~</div>
    <button
      class="navbar-toggler"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to 'ログイン', login_path ,class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation bg-dark" data-bs-theme="dark">
    <%= link_to root_path, class: 'navbar-brand '  do %>
    <%= image_tag 'logo.png', width:50 %>
    <%end %>
    <div class = "navbar-text">Reality Reflections ~あるあるを寄せ合うSNS~</div>
    
    <button
      class="navbar-toggler"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto main-nav align-items-center">
        <% if current_user %>
        <li class="navbar-text me-auto">Myあるある投稿数：<%= current_user_board_count %>　</li>
        <li class="navbar-text me-auto">めちゃR獲得数：<%= current_user.total_majors_received %>　</li>
        <li class="navbar-text me-auto">シブR獲得数：<%= current_user.total_minors_received %>　</li>
        <% else %>
        <% end %>
        <li class="nav-item dropdown dropdown-slide">
          <%= link_to current_user.displayname, "#", class: 'nav-link dropdown-toggle', data: {bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false'}, id: 'header-board-menu' %>
          <div class="dropdown-menu dropdown-menu-end">
            <%= link_to 'あるある見たい', boards_path, class: 'dropdown-item' %>
            <%= link_to 'あるある言いたい', new_board_path, class: 'dropdown-item' %>
            <%= link_to 'ログアウト', logout_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
          </div>
        </li>
        </li>
      </ul>
    </div>
  </nav>
</header>