config/routes.rb
Rails.application.routes.draw do
  root "staticpages#top"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: %i[new create]
  # resources :boards, only: %i[index new create destroy]
  get 'login', to: 'user_session#new'
  post 'login', to: 'user_session#create'
  delete 'logout', to: 'user_session#destroy'
  get "up" => "rails/health#show", as: :rails_health_check
  # 追加 新しいguest_majorレコードを作成する
  resources :guest_majors, only: [:create]
  # 追加 ランダムにboardを2つ選び、それらをJSON形式で返す
  get 'boards/random', to: 'boards#random_boards'
  get 'boards/which_major', to: 'boards#which_major'
  resources :boards do
    resource :majors, only: [:create, :destroy]
    resource :minors, only: [:create, :destroy]
  end
  
end

app/models/board.rb
class Board < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :majors, dependent: :destroy
  has_many :minors, dependent: :destroy
  has_many :guest_majors, dependent: :destroy
  validates :body, length: { maximum: 140 }, presence: true
  validates :category, presence: true

  def majors_count
    majors.count
  end
  def minors_count
    minors.count
  end
  def self.ransackable_attributes(auth_object = nil)
    %w[body category created_at majors_count minors_count guest_majors_count total_majors] 
  end
  def self.ransackable_associations(auth_object = nil)
    %w[user majors minors guest_majors] # 検索可能な関連付けをここにリストアップ
  end
  def guest_majors_count
    guest_majors.count
  end
  # 仮想属性の定義
  def total_majors
    majors_count + guest_majors_count
  end

  #ransacker :majors_count do
    #query = '(SELECT COUNT(majors.id) FROM majors WHERE majors.board_id = boards.id GROUP BY majors.board_id)'
    #Arel.sql(query)
  #end
  #
  ransacker :total_majors do
    Arel.sql('majors_count + guest_majors_count')
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: %i[index which_major random_boards]
  
  def index
      @q = Board.ransack(params[:q])
      @boards = @q.result.includes(:user).order(created_at: :desc).page(params[:page]).per(10)
      @board = Board.new
  end

  def show
    @board = Board.find(params[:id])
  end

  def new
    @board = Board.new
  end

  def edit; end

  def create
    @board = Board.new(board_params)
    @board.user = current_user
    begin
      prompt = "purpose：あるある事例を紹介したい, situation：#{@board.category}, detail：#{@board.body}, constraints：without subtitles"
      image_key = ChatgptService.download_image(prompt)
      @board.image.attach(ActiveStorage::Blob.find_by(key: image_key)) if image_key
    rescue Net::ReadTimeout
      flash.now['danger'] = I18n.t('ja.board.failed_post_aruaru', item: Board.model_name.human)
      render :new, status: :unprocessable_entity
    end
    
    if @board.image.attached? && @board.image.filename.to_s != ""
      if @board.save
        redirect_to boards_path, success: I18n.t('board.post_aruaru', item: Board.model_name.human)
      else
        Rails.logger.debug(@board.errors.full_messages)
        flash.now['danger'] = I18n.t('board.failed_post_aruaru', item: Board.model_name.human)
        render :new, status: :unprocessable_entity
      end      
    else
      Rails.logger.debug(@board.errors.full_messages)
      flash.now['danger'] = I18n.t('board.failed_post_aruaru', item: Board.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def update; end

  def destroy
    @board.destroy!
    redirect_to boards_path, success: t('board.delete_aruaru', item: Board.model_name.human)
  end

  # 新規追加 ランダムなboardを2つ選ぶ
  def random_boards
    boards = Board.order("RANDOM()").limit(2)
    boards_with_image_urls = boards.map do |board|
      image_url = board.image.attached? ? url_for(board.image.variant(resize: "512x512")) : nil
      board.attributes.merge({ image_url: image_url })
    end

    render json: boards_with_image_urls
  end

  # 新規追加　あるある選択ページ
  def which_major
    @boards = Board.all
  end


  private
  
  def set_board
    @board = current_user.boards.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:category, :body)
  end
end

app/views/boards/_board.html.erb
<div class="card mt-3 mx-3 p-0" style="width: 18rem;">
	<div class="card-img-top">
  <% if board.image.attached? %>
    <%= image_tag board.image.variant(resize: "512x512"), class: 'img-fluid' %>
  <% end %>
   <div class="card-img-overlay">
      <h6><span class="badge bg-secondary"><%= board.category %></span></h6>
    </div>
  </div>
	
	<div class="card-title text-center card-header">
   <h5><%= board.user.displayname %></h5>
  </div>
  <div class="card-body">
    <p class="card-text">
      <%= board.body %>
    </p>
  </div>
  
  <div class="d-grid gap-2 d-md-block m-3">
  <% if logged_in? %>
    <% if board.majors.find_by(user: current_user) %>
      <%= render 'boards/unmajor', {board: board} %>
    <% else %>
      <%= render 'boards/major', {board: board} %>
    <% end %>

    <% if board.minors.find_by(user: current_user) %>
      <%= render 'boards/unminor', {board: board} %>
    <% else %>
      <%= render 'boards/minor', {board: board} %>
    <% end %>
  <% else %>
    <button type="button" class="btn btn-outline-primary" disabled><%= "#{board.majors_count+board.guest_majors_count}めちゃR" %></button>
    <button type="button" class="btn btn-outline-secondary" disabled><%= "#{board.minors_count}シブR" %></button>
  <% end %>
  <i class="bi bi-question-circle" data-bs-toggle="modal" data-bs-target="#RSample"></i>
  </div>

  <div class="text-end card-footer">
    <small class="text-muted">
      <%= board.created_at.strftime("%Y-%m-%d %H:%M") %>
    </small>
    <% if logged_in? %>
    
      <%= render 'crud_menus', board: board if current_user.own?(board) %>
    <% end %>
  </div>

</div>


<div class="modal fade" id="RSample" tabindex="-1" aria-labelledby="#RSample" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">RR（あるある）評価</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p><button type="button" class="btn btn-primary" disabled>めちゃR</button> : 日常的に遭遇する物量的あるある　ほんとそれな</P>
      　<p><button type="button" class="btn btn-secondary" disabled>シブR</button> : 頻度は低いが深みのある技巧派あるある　わかるわぁ</P>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Recognise</button>
      </div>
    </div>
  </div>
</div>


<!-- X投稿モーダル　-->
<div class="modal fade" id="X" tabindex="-1" aria-labelledby="XLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="XLabel"><%= "あるあるをXに投稿しますか？" %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="text-end">
       <div class="modal-footer">
        <%= link_to 'はい', "https://twitter.com/share?url=https://rr-8cbq.onrender.com/boards&text=【あるあるを寄せ合うSNS】投稿しました！%0a %0a『#{CGI.escape(board.body)}』%0a %0a%23あるある %23RUNTEQ%0a",  
        class: 'btn btn-primary',
        target: '_blank' %>
      </div> 
      </div>
    </div>
  </div>
</div>

app/views/boards/_crud_menus.html.erb
<button type="button" class="btn btn-dark btn-sm bi bi-twitter-x" data-bs-toggle="modal" data-bs-target="#X"></button>
<%= link_to "Remove", board_path(board), id: "button-delete-#{board.id}", data:{turbo_method: :delete, turbo_confirm: t('defaults.message.delete_confirm')}, class: ' btn btn-danger btn-sm'%>

app/views/boards/_form.html.erb
<%= form_with model: board, local: true do |f| %>
<div class="new_board">
  <div class="mb-3">
    <!-- name属性はform_withの自動付与に任せれば明示する必要はない-->
    <%= f.label :category, t('activerecord.attributes.board.category')%>
    <%= f.select :category, options_for_select(['','プログラミング', '日常・休日', '仕事', 'アニメ・漫画などの展開','性格・特性']), {}, class: 'form-control' %>
  </div>
</div>
<div class="mb-3">
  <%= f.label :body, t('activerecord.attributes.board.body') %>
  
  <!-- フォームのテキストエリアの入力幅はstyleで指定するのではなく、rows: で設定したほうがよい -->
  <%= f.text_area :body, class: 'form-control mt-2', rows: 5, placeholder: "誰が・どこで・どんな時に・何を・どうなった・・・できる限り具体的に。" %>
</div>
<div class="text-end">
<%= f.submit  t('board.create_button'),class: 'btn btn-secondary' %>
</div>
<% end %>

app/views/boards/_major.html.erb
<%= link_to board_majors_path(board), 
                  data: { turbo_method: :post},
                  class: "btn btn-outline-primary btn-sm",
                  id: "major-button-for-board-#{board.id}" do %>
<%= "#{board.majors_count+board.guest_majors_count}めちゃR" %>
<% end %>

app/views/boards/_minor.html.erb
<%= link_to board_minors_path(board), 
                  data: { turbo_method: :post},
                  class: "btn btn-outline-secondary btn-sm",
                  id: "minor-button-for-board-#{board.id}" do %>
<%= "#{board.minors_count}シブR" %>
<% end %>

app/views/boards/_unmajor.html.erb
<%= link_to board_majors_path(board), 
                  data: { turbo_method: :delete},
                  class: "btn btn-primary btn-sm",
                  id: "unmajor-button-for-board-#{board.id}" do %>
<%= "#{board.majors_count+board.guest_majors_count}めちゃR" %>
<% end %>

app/views/boards/_unminor.html.erb
<%= link_to board_minors_path(board), 
                  data: { turbo_method: :delete },
                  class: "btn btn-secondary btn-sm",
                  id: "unminor-button-for-board-#{board.id}" do %>
<%= "#{board.minors_count}シブR" %>
<% end %>

app/views/boards/index.html.erb
<div class="row m-1">
    <div class="col-12">
      <div class="row">
        <%= search_form_for @q do |f| %>
        <div class="input-group mt-3">
          <%= f.search_field :user_displayname_cont, class:"form-control m-1", placeholder:"ユーザー"%>
          <%= f.select :category_cont, ['プログラミング', '日常・休日', '仕事', 'アニメ・漫画などの展開','性格・特性'], { include_blank: 'カテゴリーを選択' }, class: 'form-control m-1' %>
          <%= f.search_field :body_cont, class:"form-control m-1", placeholder:"あるある本文"%>
          <%= f.submit "Search" ,class:"btn btn-primary m-1"%>
        </div>
        <% end %>
        <div class="btn-group-sm text-end" role="group" aria-label="Basic example">
          Sort
          <%= sort_link(@q, :created_at, "投稿日", {}, { class: "btn btn-primary" }) %>
          <%= sort_link(@q, :total_majors, "めちゃR数", {}, { class: "btn btn-primary" }) %>
          <%= sort_link(@q, :minors_count, "シブR数", {}, { class: "btn btn-primary" }) %>
        </div>
      </div>
      <%= paginate @boards %>
      <div class="row">
        <% if @boards.present? %>
          <% if logged_in? %>
            <div class="fixed-bottom text-end" style="padding-right: 20px; padding-bottom: 10px;">
            <button type="button" class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#newBoardModal">投稿する</button>
            </div>
          <% else %>
            <div class="alert alert-primary mt-3" role="alert">
              ログインすると投稿と評価が可能になります
            </div>
          <%end%>
    
        <%= render partial: "board", collection: @boards %>
        <% else %>
        <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>
<div class="mb-5">
  <%= paginate @boards %>
  <p> </p>
</div>





<!-- モーダル -->
<div class="modal fade" id="newBoardModal" tabindex="-1" aria-labelledby="newBoardModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newBoardModalLabel"><%= t('boards.title') %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <!-- ここにフォームを挿入 -->
        <%= render 'form', { board: @board } %>
      </div>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('boards.title') %></h1>
      <%= render 'form', { board: @board } %>
    </div>
  </div>
</div>

app/views/boards/which_major.html.erb
<div class="d-flex justify-content-center align-items-center vh-80 m-5">
   <div class="container mx-auto bg-light">
    <div class="mt-3">
    <h2><b>どっちがmoreあるある？</b><h2>
    </div>
    
    <div class="mb-5">  
      <div id="boards-container" class="row">

        <%= javascript_include_tag 'boards' %>

      </div>
    </div>
    <%= link_to boards_path do %>
    <button type="button" class="btn btn-primary btn-lg">一覧をみる</button>
    <% end %>
    <%= link_to new_board_path do %>
    <button type="button" class="btn btn-primary btn-lg">投稿する</button>
    <% end %>

  </div>
  
</div>